### ISSUE TITLE
Exception when tour finishes or skip button pressed

### ISSUE THREAD

**Issue by abulka** [GlobalHive/vuejs-tour#18]
I am using vite and vue 3 and the demo tour works OK but raises an exception when I hit `finish` or hit `skip` at any point in the tour.

```
TypeError: Cannot read properties of null (reading 'classList')
```

![image](https://user-images.githubusercontent.com/11467530/211253507-2c43f517-8d18-4e12-ac08-676329a7b6a3.png)

I've tried both the autoStart and manual start technique, but it makes no difference. 

See https://stackblitz.com/edit/vitejs-vite-h9ayf3?file=src/App.vue

**Comment by GlobalHive** [comment]
Hello, thanks for this issue
You're right, i didn't check if you're using the highlight or not.
Fixed in version v1.3.3 #19 (NPM Updated)
