### ISSUE TITLE
bug and optimization

### ISSUE THREAD

**Issue by wang135309** [GlobalHive/vuejs-tour#20]
If I increase the highlight property, an error will be generated and the highlight will not be displayed for the first time
I think it should be caused by the initial value of lastStep being null.
![signal-2023-01-13-144243_002](https://user-images.githubusercontent.com/31681041/212255087-c45015ad-119b-4517-a7d4-0487b4518947.png)
![signal-2023-01-13-144243_003](https://user-images.githubusercontent.com/31681041/212255101-f1b3321a-a0f6-4017-b632-0f9a64241e39.png)
In addition, is it possible to increase the properties of a mask layer?

**Comment by GlobalHive** [comment]
Hey, thanks for your issue
I'm going to check this as soon as im at home.

What do you mean by "Increase the properties of a mask layer"

Sincerey,
Sascha

**Comment by wang135309** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/31681041/212584903-651689c4-a25a-4f74-84eb-9f5120e88775.png">
Effect like this, can allow whether to display the mask layer

**Comment by GlobalHive** [comment]
Thanks for the clarification,
i'll look into it

Sincerely,
Sascha
