### ISSUE TITLE
Hide Previous button on #actions overwrite

### ISSUE THREAD

**Issue by svenphilipsen** [GlobalHive/vuejs-tour#25]
When overwriting the #actions template to get your own labels on button, the hiding of the "previous button" on first step is not activated anymore. To hide it the same way as in the VTour.vue file we would have to be able to access the currentStep prop value - can it therefor be made available?

```vue
<VTour :steps="steps" startDelay='1000' autoStart highlight>
    <template #actions="{ nextStep, prevStep }">
        <div class="vjt-actions">
            <button type="button" @click.prevent="prevStep">Go back</button>
            <button type="button" @click.prevent="nextStep">Go on</button>
        </div>
    </template>
</VTour>
```

**Comment by svenphilipsen** [comment]
The same is the case for my "Go on" button, when I want it to become a "Finish" button.

**Comment by GlobalHive** [comment]
Good catch 👍 
I'll add it as soon as i'm back from vacation
