### ISSUE TITLE
ButtonLabel "skip" hardcoded

### ISSUE THREAD

**Issue by kypergio** [GlobalHive/vuejs-tour#27]
Two issues found:
1. Documentation incorrect about **buttonLabel** property which should be **buttonLabels** instead.
2. Skip text is hardcoded, it should be read from component's props.

![image](https://github.com/GlobalHive/vuejs-tour/assets/23042911/3f237206-119b-4d5a-9e09-9077bb38c1f6)

**Comment by GlobalHive** [comment]
Fixed in release 1.3.6
Update over NPM #closed
