### ISSUE TITLE
Popper: Invalid reference or popper argument provided.

### ISSUE THREAD

**Issue by popdo** [GlobalHive/vuejs-tour#35]
When using the `VTour ` component in `app.vue`, if the rendering of the child component is slow, it will cause the following error message and cannot run properly:

```
Popper: Invalid reference or popper argument provided. They must be either a DOM element or virtual element.
```

Do you have any good solutions?

**Comment by ThorntonStuart** [comment]
@popdo did you find a solution to this?

**Comment by popdo** [comment]
> @popdo did you find a solution to this?

You just need to set a delay time on the props.
