### ISSUE TITLE
Bouncing

### ISSUE THREAD

**Issue by sharperDev2112** [GlobalHive/vuejs-tour#36]
This is a great package. Thanks for your work on it. *Minor* issue here...

When I'm taking a tour and click Next, the screen scrolls to the next target. During the scroll the step content is displayed but it bounces. I assume it is continually readjusting its position. Is there a way to alter the scroll speed or hide the content until scrolling is finished so we don't see that stuttering?

I am using @globalhive/vuejs-tour version ^1.3.7 in a Vue app version 3.2.33.

Thanks.

**Comment by GlobalHive** [comment]
Hi @sharperDev2112 

Thank you for raising this issue! 🙌 I appreciate your diligence in reporting it. I'll dive into the matter ASAP and keep you posted on my progress. If you have any additional details or insights, feel free to share.

Thanks again for your contribution to the project! 👏

Best regards,
Sascha
Global Hive

**Comment by GlobalHive** [comment]
Hello @sharperDev2112 
sadly I could not reproduce your issue.

I created a new project, added the latest version, and set up a scrolling situation.
As you can see...
![Issue](https://github.com/GlobalHive/vuejs-tour/assets/20327081/04fa8ed8-e752-4f58-b61c-bddfd457c921)

there's no jumping.
The used element is placed in the new position as soon as you click on "next"
This means it does not move along, it literally "teleports" there regardless of the document setup.

Maybe you can give more insight on what you did, or create an example project with the jumping.
Best regards,
Sascha
Global hive

**Comment by sharperDev2112** [comment]
I'm not sure why my page is scrolling since these (not all) targets are in the fixed header...(3rd one bouncing a bit)

![Bounce](https://github.com/GlobalHive/vuejs-tour/assets/48840739/5b9ede9d-2455-4875-a1ff-1f9eae4ea323)

But I'm good with you closing this. I'm probably doing something wrong. If I'm able to isolate this in a test project I will forward it.... Thanks.

**Comment by sharperDev2112** [comment]
After further review I believe my scrolling issue is due to me hosting the control too deep in component hierarchy (which is probably why you tell users to host in app.vue :) ). I did that to make it easier to launch but I will fix. Thanks again!
