### ISSUE TITLE
The result saving customisation

### ISSUE THREAD

**Issue by RafRaf** [GlobalHive/vuejs-tour#39]
It would be nice to have an option to turn on and off the result storing in `localStorage`. I would like to store the result on my own and it looks like it isn't possible right now.

**Comment by GlobalHive** [comment]
Hi @RafRaf 

Thanks for raising the issue. I've added it to our backlog for future implementation. While I can't provide an exact timeline, rest assured it's on our radar. Your input is valuable, and we appreciate your patience.

Best,
@GlobalHive

**Comment by GlobalHive** [comment]
Hi @RafRaf 

Your request has been added.

1.  Update package to 1.4.0
2. Add saveToLocalStorage to your VTour component:
`<VTour :steps="steps" saveToLocalStorage='custom'/>`
OR if you want every step to be saved:
`<VTour :steps="steps" saveToLocalStorage='step'/>`
3. If 'custom' is used, the component won't save anything, so its up to you how you wanna do it.
4. Profit!

[Docs](https://globalhive.github.io/vuejs-tour/guide/props.html)

Best,
@GlobalHive
