### ISSUE TITLE
Extra features

### ISSUE THREAD

**Issue by Ktsirakos** [GlobalHive/vuejs-tour#42]
Hello @GlobalHive

Just came across this plugin trying to make vue-tours work with Vue3. 
Happy that I found yours work as a charm. 

I aim to use this plugin for creating multi-page onboarding tutorials for my webapp, therefore I need some more utility functions to possibly achieve that.

Requirements: 
- Being able to run a tour over and over again (I got around that by sending `save-to-local-storage="nope"` to not store in the local-storage that the tour was completed)
- Being able to jump to a certain step (maybe a function called `goToStep`)
- Being able to NOT show neither `Next` or `Finish` (this is to prompt the user to do an action like press a button that will lead him to another page and thus continue the tour from there)

Thank you very much in advance :)

**Comment by GlobalHive** [comment]
Hi @Ktsirakos,

If you don't want to save the tour state, use `saveToLocalStorage="custom"` or any value other than `"step"` or `"end"`

To hide `"Back / Next / Finish,"` customize the `"action slot"` and leave it empty. Check [this link](https://globalhive.github.io/vuejs-tour/guide/methods.html#action-slot-methods) for more details.

I'll add the `goToStep ` as soon as possible. (Might be added in 1-2 days)

Sincerely,
Sascha
Global Hive

**Comment by GlobalHive** [comment]
Feature request has been added.

To use it create a ref to the VTour component. Then call the goToStep() function

`vTour.value.goToStep(2)`
