### ISSUE TITLE
Customization & Localizaation

### ISSUE THREAD

**Issue by franck102** [GlobalHive/vuejs-tour#46]
Is there any way to customize and/or localize the plug-in? I would need to replace the "Skip" and "Finish" labels in the tooltip.

**Comment by ordago** [comment]
You have too use these props:

https://github.com/GlobalHive/vuejs-tour/blob/022a6611bf2becafefc506ed5f82b58238bf42db/src/components/VTour.vue#L62-L72

**Comment by GlobalHive** [comment]
Exactly as @ordago answered.
#closed
