### ISSUE TITLE
Hide tour when selector is not found

### ISSUE THREAD

**Issue by BayBreezy** [GlobalHive/vuejs-tour#48]
Hello @GlobalHive ,

Thanks for the package, really appreciate it.

I noticed that when a selector that does not exist in the DOM is add to a step(the starting step), an error is logged and the tour is displayed at the bottom corner of the web page.

This is the error logged in the browser

```bash
Uncaught TypeError: Cannot read properties of null (reading 'classList')
```

And then this is what it looks like in the bottom corner

![image](https://github.com/GlobalHive/vuejs-tour/assets/53905713/72ed0a3d-1bd2-46e8-82a2-472dfc2fc5c2)

Notice the page now overflows even tho i set it to be 100vh.

I fixed it by adding the correct selector but I thought it would be nice to let you know of this issue.

**Comment by GlobalHive** [comment]
Hello @BayBreezy 
If a selector is not found, it jumps to the next one.

If there is only one, then you're right.
I'm going to add a security check and hide the element.

Sincerely,
Sascha

**Comment by BayBreezy** [comment]
Thanks. Btw, I might make a module out of this package for nuxt.. I will make some changes to the code if that is alright with you. I saw the MIT license, just felt like giving a heads up :)

**Comment by GlobalHive** [comment]
Yeah no problem, just make sure to keep me in there 😅

**Comment by BayBreezy** [comment]
Hey @GlobalHive , I published the nuxt version. 

https://nuxt-tour.behonbaker.com/
Repo: https://github.com/BayBreezy/nuxt-tour

**Comment by GlobalHive** [comment]
Hello @BayBreezy 
i just fixed your issue, i am going to push an update today.
Now if there's no step, it goes to the next one until it just ends.

The errors will still be show in console so you know whats wrong.
Sincerely,
Sascha

**Comment by BayBreezy** [comment]
Thank you
