### ISSUE TITLE
Could not find a declaration file for module '@globalhive/vuejs-tour'

### ISSUE THREAD

**Issue by kopiaman** [GlobalHive/vuejs-tour#53]
<img width="889" alt="Screenshot 2024-04-24 at 10 11 47 AM" src="https://github.com/GlobalHive/vuejs-tour/assets/8829509/7ac55c59-4d6f-4b7e-9be9-aca7f37e20ed">

**Comment by GlobalHive** [comment]
Hey @kopiaman 
that's weird since no one else ever has this problem.
Can you give me some information about the project (versions e.c.t)

Best Regards,
Sascha

**Comment by GlobalHive** [comment]
Looks like you're using it in a Typescript project.
VueJS-Tour is written in JavaScript (for now, going to migrate soon)

To avoid the issue just replace these line in the tsconfig.json

```
"noImplicitAny": false,
"allowJs": true,
```

then it should work without a Problem

Best Regards,
Sascha
