### ISSUE TITLE
resetTour doesn't clean 'vjt-default' from localStorage

### ISSUE THREAD

**Issue by Clement-Bretin** [GlobalHive/vuejs-tour#54]
It seems that .resetTour(); doesnt remove 'vjt-default' or set it to false;
So the tooltips never appear a second time. (stay hidden)

Possible to have an option to not use localStorage and always show the tour on start ? 
`
 if(props.saveToLocalStorage === 'end' || props.saveToLocalStorage === 'step') localStorage.setItem("vjt-" + props.name, "false"); 
}`

Thanks

**Comment by GlobalHive** [comment]
Hi @Clement-Bretin ,

Thank you for bringing this to my attention. I appreciate your report. I'll review this as soon as possible and let you know the progress.

Best regards,
Sascha

**Comment by GlobalHive** [comment]
Hey @Clement-Bretin,
this issue has been resolved, please update the NPM package.

Put "saveToLocalStorage" to anything other than "end" or "step"
Most use "custom" so it doesn't handle any saving by it self, so you're the one
responsible for providing your own saving system.

Sincerely,
Sascha

#55 #Closed
