### ISSUE TITLE
Split backdrop into 4 divs around highlighted div

### ISSUE THREAD

**Issue by chboing** [GlobalHive/vuejs-tour#67]
See comment here : https://github.com/GlobalHive/vuejs-tour/issues/65#issuecomment-2331124090

Some libraries are redefining stacking context, so it's impossible to use the backdrop as it is now.
This could be switched on/off on demand with a prop. Not necessarily a "quasar" props, since it's probably not the only framework to be impacted.

**Comment by GlobalHive** [comment]
Thank you for creating this issue! I'll start working on it ASAP. 🙏

**Comment by GlobalHive** [comment]
Hello @chboing ,

I have updated the highlight procedure to use the `clip-path` for the backdrop, as mentioned in #68. This ensures compatibility across all frameworks.

There is no need for any changes on your end. Simply update the package to version 2.2.0.

Best regards,
Global Hive
Sascha

**Comment by chboing** [comment]
You may want to update your doc too ;) https://globalhive.github.io/vuejs-tour/guide/the-onbefore-event.html
I was waiting the 2.2.0 with this feature (onBefore & onAfter) but it seems i'll have to wait a bit more !

**Comment by GlobalHive** [comment]
Hey @chboing,
You're right, looks like the latest release went out without the Dev branch included—oops! I’ve just pushed a new one, and it’s got all the, bigger, promised features now.

Best regards,
Global Hive
Sascha
