### ISSUE TITLE
Error trying to use this on Nuxt3

### ISSUE THREAD

**Issue by enzortk** [GlobalHive/vuejs-tour#72]
Cannot read properties of undefined (reading '0')
 I tried to use it directly and also as a plugin but I get the error 
 
![image](https://github.com/user-attachments/assets/43b10f53-0b5e-4212-a77a-262b57cd6033)

**Comment by GlobalHive** [comment]
Hello @enzortk 
can you show me how you added VueJS to your project?

Best Regards,
Sascha
