### ISSUE TITLE
OnBefore Promise Bug

### ISSUE THREAD

**Issue by michaelpelletier** [GlobalHive/vuejs-tour#73]
There is an order-of-operations bug with using Promises in an `onBefore`

<img width="435" alt="Screenshot 2024-10-18 at 4 15 35 PM" src="https://github.com/user-attachments/assets/31d7029d-5284-4649-8d1a-26102b542cf8">

OnBefore is called within `updatePosition` which means if you're trying to do something involved in delaying it, the text has already updated to the next step before your onBefore even fires, putting you into an awkward non-state. 

My use case is that for the tour I am changing pages, so I need to fire a router push in between steps. As written now, this code will move me on to the next step _before_ the page changes. 

The _easy_ solution is to move the `updatePosition` call to be earlier, but I think that runs into the problem then that `updatePosition` _also_ calls the `onAfter` which would then likely be out of sync in the same (inverted) way. 

I'll open a PR in a little bit but my proposed solution is to split this up into multiple calls, essentially:
- OnBefore
- UpdatePosition
- UpdateContent
- OnAfter

**Comment by michaelpelletier** [comment]
Update because I misread something: `backdrop` _is_ per step, which makes `onBefore` even more of an unclear outlier (and possibly just an actual bug? I didn't dig into the source).

**Comment by GlobalHive** [comment]
Hey @michaelpelletier 
Thanks for this issue.

I will check your PR today evening as soon as im at home.

Best Regards,
Sascha

**Comment by GlobalHive** [comment]
Very well done!
I merged your PR, and updated the package everywhere. #75 

Best Regards,
Sascha
