### ISSUE TITLE
saveToLocalStorage saves all Tours

### ISSUE THREAD

**Issue by dPasz** [GlobalHive/vuejs-tour#81]
I use vTour on 2 components, but with a different tour and steps. When i finish one and i use saveToLocalStorage="end" then the second vTour on the other component also is saved as done. It would be better to save each ref of vTour alone so you could check which tour on which component got completed

**Comment by GlobalHive** [comment]
Hey @dPasz 
this is already possible.

Give your tour a name through the "name" prop and it will get saved in different properties.

See [Multiple Tours](https://globalhive.github.io/vuejs-tour/guide/multiple-tours.html) on the docs

Best Regards,
Sascha
